In [11]:
import numpy as np

In [2]:
a= np.array([1,2,3])
b= np.array([[1,2] , [3,4]])
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [4]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int64


In [5]:
a = np.array([1,2,3,4,5,6])
print(a.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [9]:
arr = np.array([10,20,30,40,50])
print(arr[1])
print(arr[1:4])

20
[20 30 40]


In [21]:
print(np.zeros((2, 3)))

print(np.ones((3, 3,)))

print(np.eye(3,3))

print(np.full((2,2),7))

print(np.arange(1, 10, 2))

print(np.linspace(1, 5, 4))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7 7]
 [7 7]]
[1 3 5 7 9]
[1.         2.33333333 3.66666667 5.        ]


In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)
print(a ** 2)
print(np.sqrt(a))
print(np.mean(a))

[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]
2.0


In [17]:
arr = np.array([[1,2,3] , [4,5,6]])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))

21
1
6
[5 7 9]
[ 6 15]


In [18]:
arr = np.array([[1,2] , [3,4]])
print(arr.flatten())

[1 2 3 4]


In [19]:
arr = np.array([[1,2,3] , [4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [20]:
a = np.array([[1,2] , [3,4]])
b = np.array([[2,0] , [1,2]])
print(np.dot(a,b))

[[ 4  4]
 [10  8]]
