In [2]:
import numpy as np

In [3]:
#Create a NumPy array of integers from 0 to 10.
arr1 = np.arange(11)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [6]:
#create an array of 10 zeros and chamge the 5th value to 1
arr2 = np.zeros(10)
arr2[4] = 1
print(arr2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
#Generate an array of 10 ones.
arr2 = np.ones(10)
print(arr2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
#Create a 1D array of 20 equally spaced numbers between 0 and 1
arr4 = np.linspace(0, 1, 20)
print(arr4)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [10]:
#Create a 3x3 identity matrix.
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#Create a 4x4 matrix with values from 0 to 15.
a = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(a.reshape(4,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [12]:
#Generate a 5x5 matrix with random values.
arr7 = np.random.rand(5, 5)
print(arr7)

[[0.16045611 0.89168272 0.56162838 0.28026378 0.08859276]
 [0.29353962 0.44851455 0.6364109  0.94354681 0.18856938]
 [0.72272196 0.72788655 0.98343852 0.21363563 0.81616813]
 [0.18207878 0.26134171 0.97284408 0.4261822  0.39755677]
 [0.09598317 0.06809503 0.58833878 0.77286536 0.00901398]]


In [14]:
#Reverse the elements of an array.
arr8 = np.array([1, 2, 3, 4, 5])
arr8reversed = arr8[::-1]
print(arr8reversed)

[5 4 3 2 1]


In [15]:
#Flatten a 2D array to 1D.
arr9 = np.array([[1, 2, 3], [4, 5, 6]])
arr9flattened = arr9.flatten()
print(arr9flattened)

[1 2 3 4 5 6]


In [16]:
#extract even number from an array 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
evennumbers = arr[arr % 2 == 0]
print("Even numbers:", evennumbers)

Even numbers: [ 2  4  6  8 10]
